//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Configuration;
namespace Ds.DataService.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=localhost;Initial Catalog=SmartCoinLocal;Persist Security Info=True;U" +
            "ser ID=sa")]
        public string SmartCoinLocalConnectionString {
            get {
                return ConfigurationManager.ConnectionStrings["SQLConnectionString"].ConnectionString;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=190.8.176.202\\MSSQLSERVER2012;Initial Catalog=estadi_SmartCoinCentral" +
            ";Persist Security Info=True;User ID=estad_123456")]
        public string estadi_SmartCoinCentralConnectionString {
            get {
                return ConfigurationManager.ConnectionStrings["SQLConnectionString"].ConnectionString;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=107.180.70.70;Initial Catalog=SmartCoinCentral;Persist Security Info=" +
            "True;User ID=SA;Password=Sm4rtC0in$")]
        public string SMARTCOINConnectionString {
            get {
                return ConfigurationManager.ConnectionStrings["SQLConnectionString"].ConnectionString;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=169.47.207.158;Initial Catalog=ATMParquearse;User ID=sa;Password=M1ll" +
            "3n5")]
        public string ATMParquearseConnectionString {
            get {
                return ConfigurationManager.ConnectionStrings["SQLConnectionString"].ConnectionString;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=169.47.207.158;Initial Catalog=TestFlorida;User ID=sa;Password=M1ll3n" +
            "5")]
        public string TestFloridaConnectionString {
            get {
                return ConfigurationManager.ConnectionStrings["SQLConnectionString"].ConnectionString;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SERVIDOR;Initial Catalog=ParkingFlorida;User ID=sa;Password=Parquears" +
            "e123")]
        public string ParkingFloridaConnectionString {
            get {
                return ConfigurationManager.ConnectionStrings["SQLConnectionString"].ConnectionString;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.87;Initial Catalog=Parking;User ID=sa;Password=Parquearse12" +
            "3")]
        public string ParkingConnectionString {
            get {
                return ConfigurationManager.ConnectionStrings["SQLConnectionString"].ConnectionString;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.16;Initial Catalog=ParkingBosqu3;User ID=sa;Password=Parque" +
            "arse123")]
        public string ParkingBosqu3ConnectionString {
            get {
                return ConfigurationManager.ConnectionStrings["SQLConnectionString"].ConnectionString;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.87;Initial Catalog=ParkingFlorida;User ID=sa;Password=Parqu" +
            "earse123")]
        public string ParkingFloridaConnectionString1 {
            get {
                return ConfigurationManager.ConnectionStrings["SQLConnectionString"].ConnectionString;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.87;Initial Catalog=ParkingCabecera;User ID=sa;Password=Parq" +
            "uearse123")]
        public string ParkingCabeceraConnectionString {
            get {
                return ConfigurationManager.ConnectionStrings["SQLConnectionString"].ConnectionString;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.16.63.54;Initial Catalog=Parking;User ID=sa;Password=Parquearse12" +
            "3")]
        public string ParkingConnectionString1 {
            get {
                return ConfigurationManager.ConnectionStrings["SQLConnectionString"].ConnectionString;
            }
        }
    }
}
